# Generated by Django 5.2.10 on 2026-01-29 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['start_date'], 'verbose_name_plural': 'Cities'},
        ),
        migrations.AddField(
            model_name='city',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='is_current_expo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='city',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StallBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.city')),
                ('stall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stall')),
            ],
        ),
    ]
