# Generated by Django 5.2.10 on 2026-02-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_city_options_city_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
