# Generated by Django 5.2.10 on 2026-02-03 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_photo_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stalls', to='api.city'),
        ),
    ]
