# Generated by Django 5.2.10 on 2026-02-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_stall_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stall',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
