# Generated by Django 5.2.10 on 2026-02-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_stall_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='stallbooking',
            name='slot_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
