# Generated by Django 5.2.10 on 2026-02-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_stallbooking_slot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
