# Generated by Django 5.2.10 on 2026-02-06 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_city_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stallbooking',
            name='slot_id',
        ),
    ]
