# Generated by Django 5.2.10 on 2026-02-06 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_stallbooking_slot_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exhibitorregistration',
            old_name='category',
            new_name='location',
        ),
    ]
