# Generated by Django 5.2.10 on 2026-02-20 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_category_exhibitorregistration_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='WheelPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=50)),
                ('total_quantity', models.IntegerField(default=0)),
                ('remaining_quantity', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=10, help_text='Higher weight = higher chance')),
                ('color', models.CharField(default='#ec4899', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='participantregistration',
            name='prize_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='SpinWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(max_length=50, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_claimed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.wheelprize')),
            ],
        ),
    ]
