# Generated by Django 5.2.10 on 2026-02-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_wheelprize_participantregistration_prize_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='regional_representative',
            field=models.TextField(blank=True, null=True),
        ),
    ]
